version: "3.8"

services:
  inhouse_bot:
    image: mrtolkien/inhouse_bot
    build:
      context: .
    env_file:
    - .env

  db:
    image: postgres:alpine
    # Optional volume to save data long-term, not used in development
    # volumes:
    # - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: inhouse_bot

  adminer:
    image: adminer
    ports:
      - 8080:8080

# If you want to define a volume to save your postgres data, itâ€™s done here
# volumes:
#     pgdata:
